spring.application.name=Ecommeres

# ============================
# DATABASE
# ============================
spring.datasource.url=jdbc:postgresql://dpg-d64okf9r0fns73cbr5ng-a.oregon-postgres.render.com:5432/ecommers_n2u1
spring.datasource.username=ecommers_n2u1_user
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============================
# HIKARI
# ============================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=180000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000

# ============================
# JWT
# ============================
app.auth.tokenSecret=${JWT_SECRET}
app.auth.tokenExpirationMsec=3600000

# ============================
# LOGGING
# ============================
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG

# ============================
# RAZORPAY
# ============================
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_SECRET}

# ============================
# BREVO EMAIL
# ============================
brevo.api.url=https://api.brevo.com/v3/smtp/email
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=Glow Cosmetic App

# ============================
# SERVER
# ============================
server.port=${PORT:8080}

# ============================
# CLOUDINARY
# ============================
cloudinary.cloud_name=${CLOUDINARY_NAME}
cloudinary.api_key=${CLOUDINARY_KEY}
cloudinary.api_secret=${CLOUDINARY_SECRET}